'''
DISCLAIMER: this program is MOSTLY AI generated by Gemini for ease of JSON editing. As a result there are many bugs that could
easily have been avoided if written by me, but I'm no expert on TKinter at the moment and just needed a scaffolding tool.

This will be changed to a nicer node graph editor if there is time/willpower to do so. In the meantime it will have to do.
'''

import tkinter as tk
from tkinter import filedialog, messagebox, simpledialog, ttk
import json


class TSFGEditor:
    def __init__(self, root):
        self.root = root
        self.root.title("TSFG Editor - Passages & Journal Entries")
        self.data = {"__TextTags": {}}

        # State Tracking
        self.current_passage_id = None
        self.current_action_id = None
        self.current_global_tag = None
        self.current_je_id = None
        self.current_je_key = None

        # Create Tabs
        self.notebook = ttk.Notebook(root)
        self.notebook.pack(expand=True, fill="both")

        self.tab_main = ttk.Frame(self.notebook)
        self.tab_journal = ttk.Frame(self.notebook)

        self.notebook.add(self.tab_main, text="Story Editor")
        self.notebook.add(self.tab_journal, text="Journal Entries (JE_)")

        self._setup_main_tab()
        self._setup_journal_tab()
        self._setup_bottom_bar()

    def _setup_main_tab(self):
        # Grid config for main tab
        self.tab_main.columnconfigure(3, weight=1)
        self.tab_main.rowconfigure(1, weight=1)

        tk.Label(self.tab_main, text="Passages").grid(row=0, column=0)
        self.pass_list = tk.Listbox(self.tab_main, width=15)
        self.pass_list.grid(row=1, column=0, sticky="nsew", padx=5)
        self.pass_list.bind('<<ListboxSelect>>', self.on_passage_select)

        tk.Label(self.tab_main, text="Actions").grid(row=0, column=1)
        self.act_list = tk.Listbox(self.tab_main, width=15)
        self.act_list.grid(row=1, column=1, sticky="nsew", padx=5)
        self.act_list.bind('<<ListboxSelect>>', self.on_action_select)

        tk.Label(self.tab_main, text="Flags (Name: Val)").grid(row=0, column=2)
        self.flag_list = tk.Listbox(self.tab_main, width=15)
        self.flag_list.grid(row=1, column=2, sticky="nsew", padx=5)

        self.text_editor = tk.Text(
            self.tab_main, wrap="word", width=50, height=20)
        self.text_editor.grid(row=1, column=3, padx=10, sticky="nsew")

        btn_frame = tk.Frame(self.tab_main)
        btn_frame.grid(row=3, column=0, columnspan=3, sticky="ew", pady=5)
        tk.Button(btn_frame, text="Add Pass",
                  command=self.add_passage).pack(side="left", padx=2)
        tk.Button(btn_frame, text="Add Act", command=self.add_action).pack(
            side="left", padx=2)
        tk.Button(btn_frame, text="+Flag",
                  command=self.add_flag).pack(side="left", padx=2)
        tk.Button(btn_frame, text="-Flag",
                  command=self.remove_flag).pack(side="left", padx=2)

        tag_frame = tk.LabelFrame(
            self.tab_main, text="Global Text Tags (__TextTags)")
        tag_frame.grid(row=2, column=0, columnspan=3,
                       sticky="nsew", padx=5, pady=5)
        self.global_tag_list = tk.Listbox(tag_frame, height=4)
        self.global_tag_list.pack(side="left", fill="both", expand=True)
        self.global_tag_list.bind(
            '<<ListboxSelect>>', self.on_global_tag_select)
        tk.Button(tag_frame, text="Add Tag", command=self.add_global_tag).pack(
            side="top", fill="x")

    def _setup_journal_tab(self):
        self.tab_journal.columnconfigure(2, weight=1)
        self.tab_journal.rowconfigure(1, weight=1)

        tk.Label(self.tab_journal, text="Journal Entries").grid(
            row=0, column=0)
        self.je_list = tk.Listbox(self.tab_journal, width=20)
        self.je_list.grid(row=1, column=0, sticky="nsew", padx=5)
        self.je_list.bind('<<ListboxSelect>>', self.on_je_select)

        tk.Label(self.tab_journal, text="State Keys").grid(row=0, column=1)
        self.je_key_list = tk.Listbox(self.tab_journal, width=15)
        self.je_key_list.grid(row=1, column=1, sticky="nsew", padx=5)
        self.je_key_list.bind('<<ListboxSelect>>', self.on_je_key_select)

        self.je_text_editor = tk.Text(self.tab_journal, wrap="word", width=50)
        self.je_text_editor.grid(row=1, column=2, padx=10, sticky="nsew")

        je_btn_frame = tk.Frame(self.tab_journal)
        je_btn_frame.grid(row=2, column=0, columnspan=3, sticky="ew", pady=5)
        tk.Button(je_btn_frame, text="Add JE_",
                  command=self.add_journal_entry).pack(side="left", padx=5)
        tk.Button(je_btn_frame, text="Delete JE_",
                  command=self.delete_journal_entry).pack(side="left", padx=5)
        tk.Button(je_btn_frame, text="Add Key/State",
                  command=self.add_je_key).pack(side="left", padx=5)
        tk.Button(je_btn_frame, text="Delete Key",
                  command=self.delete_je_key).pack(side="left", padx=5)

    def _setup_bottom_bar(self):
        btn_panel = tk.Frame(self.root)
        btn_panel.pack(side="bottom", fill="x", padx=10, pady=10)

        tk.Button(btn_panel, text="Load JSON",
                  command=self.load_file).pack(side="left")

        tk.Button(btn_panel, text="SAVE CURRENT", bg="#4CAF50", fg="white",
                  command=self.save_current_text).pack(side="right", padx=10)
        tk.Button(btn_panel, text="Export JSON",
                  command=self.export_json).pack(side="right")

    # --- JOURNAL LOGIC ---
    def on_je_select(self, event):
        sel = self.je_list.curselection()
        if not sel:
            return
        self.current_je_id = self.je_list.get(sel)
        self.current_je_key = None
        self.refresh_je_keys()

    def on_je_key_select(self, event):
        sel = self.je_key_list.curselection()
        if not sel:
            return
        self.current_je_key = self.je_key_list.get(sel)
        content = self.data[self.current_je_id].get(self.current_je_key, "")
        self.je_text_editor.delete("1.0", tk.END)
        self.je_text_editor.insert("1.0", content)

    def refresh_je_list(self):
        self.je_list.delete(0, tk.END)
        for key in sorted(self.data.keys()):
            if key.startswith("JE_"):
                self.je_list.insert(tk.END, key)

    def refresh_je_keys(self):
        self.je_key_list.delete(0, tk.END)
        if self.current_je_id in self.data:
            for key in sorted(self.data[self.current_je_id].keys()):
                self.je_key_list.insert(tk.END, key)

    def add_journal_entry(self):
        name = simpledialog.askstring(
            "New Journal", "Entry Name (will be prefixed with JE_):")
        if name:
            full_id = f"JE_{name}"
            if full_id not in self.data:
                self.data[full_id] = {"0": "Initial State"}
                self.refresh_je_list()

    def delete_journal_entry(self):
        if self.current_je_id and messagebox.askyesno("Confirm", f"Delete {self.current_je_id}?"):
            del self.data[self.current_je_id]
            self.current_je_id = None
            self.refresh_je_list()
            self.je_key_list.delete(0, tk.END)

    def add_je_key(self):
        if not self.current_je_id:
            return
        key = simpledialog.askstring(
            "New Key", "State key (e.g. 1, thrumb, etc):")
        if key:
            self.data[self.current_je_id][key] = ""
            self.refresh_je_keys()

    def delete_je_key(self):
        if self.current_je_id and self.current_je_key:
            del self.data[self.current_je_id][self.current_je_key]
            self.current_je_key = None
            self.refresh_je_keys()

    # --- SHARED LOGIC ---
    def save_current_text(self):
        tab_idx = self.notebook.index("current")

        # Saving Story Tab
        if tab_idx == 0:
            txt = self.text_editor.get("1.0", "end-1c")
            if self.current_global_tag:
                try:
                    self.data["__TextTags"][self.current_global_tag] = json.loads(
                        txt)
                except:
                    messagebox.showerror("Error", "Invalid JSON")
            elif self.current_action_id:
                self.data[self.current_passage_id]["Actions"][self.current_action_id]["TextContent"] = txt
            elif self.current_passage_id:
                self.data[self.current_passage_id]["TextContent"] = txt

        # Saving Journal Tab
        else:
            if self.current_je_id and self.current_je_key:
                txt = self.je_text_editor.get("1.0", "end-1c")
                self.data[self.current_je_id][self.current_je_key] = txt

        messagebox.showinfo("Saved", "Memory Updated.")

    # --- REST OF REFACTORED ORIGINAL LOGIC ---
    def update_text(self, content):
        self.text_editor.delete("1.0", tk.END)
        self.text_editor.insert("1.0", content)

    def on_passage_select(self, event):
        sel = self.pass_list.curselection()
        if not sel:
            return
        self.current_passage_id = self.pass_list.get(sel)
        self.current_action_id = None
        self.current_global_tag = None
        self.update_text(
            self.data[self.current_passage_id].get("TextContent", ""))
        self.refresh_action_list()
        self.flag_list.delete(0, tk.END)

    def on_action_select(self, event):
        sel = self.act_list.curselection()
        if not sel:
            return
        self.current_action_id = self.act_list.get(sel)
        self.current_global_tag = None
        action_data = self.data[self.current_passage_id]["Actions"][self.current_action_id]
        self.update_text(action_data.get("TextContent", ""))
        self.refresh_flag_list()

    def on_global_tag_select(self, event):
        sel = self.global_tag_list.curselection()
        if not sel:
            return
        self.current_global_tag = self.global_tag_list.get(sel)
        self.current_action_id = None
        tag_data = self.data["__TextTags"][self.current_global_tag]
        self.update_text(json.dumps(tag_data, indent=4))

    def refresh_action_list(self):
        self.act_list.delete(0, tk.END)
        actions = self.data[self.current_passage_id].get("Actions", {})
        for a_id in actions.keys():
            self.act_list.insert(tk.END, a_id)

    def refresh_flag_list(self):
        self.flag_list.delete(0, tk.END)
        flags = self.data[self.current_passage_id]["Actions"][self.current_action_id].get(
            "setFlags", {})
        for name, val in flags.items():
            self.flag_list.insert(tk.END, f"{name}: {val}")

    def add_flag(self):
        if not self.current_action_id:
            return
        flag_name = simpledialog.askstring("New Flag", "Flag Name:")
        if flag_name:
            flag_val = simpledialog.askinteger(
                "Value", "Value:", initialvalue=1)
            if flag_val is not None:
                self.data[self.current_passage_id]["Actions"][self.current_action_id]["setFlags"][flag_name] = flag_val
                self.refresh_flag_list()

    def remove_flag(self):
        sel = self.flag_list.curselection()
        if not sel:
            return
        flag_name = self.flag_list.get(sel).split(":")[0]
        del self.data[self.current_passage_id]["Actions"][self.current_action_id]["setFlags"][flag_name]
        self.refresh_flag_list()

    def load_file(self):
        path = filedialog.askopenfilename()
        if path:
            with open(path, 'r') as f:
                self.data = json.load(f)
            self.pass_list.delete(0, tk.END)
            for p_id in sorted(self.data.keys()):
                if p_id != "__TextTags" and not p_id.startswith("JE_"):
                    self.pass_list.insert(tk.END, p_id)
            self.global_tag_list.delete(0, tk.END)
            for t_id in self.data.get("__TextTags", {}).keys():
                self.global_tag_list.insert(tk.END, t_id)
            self.refresh_je_list()

    def export_json(self):
        path = filedialog.asksaveasfilename(defaultextension=".json")
        if path:
            with open(path, 'w') as f:
                json.dump(self.data, f, indent=4)

    def add_passage(self):
        new_id = simpledialog.askstring("New Passage", "Passage ID:")
        if new_id and new_id not in self.data:
            self.data[new_id] = {"TextContent": "", "Actions": {}}
            self.pass_list.insert(tk.END, new_id)

    def add_action(self):
        if not self.current_passage_id:
            return
        a_id = simpledialog.askstring("New Action", "Target Passage ID:")
        if a_id:
            self.data[self.current_passage_id]["Actions"][a_id] = {
                "TextContent": "", "setFlags": {}}
            self.refresh_action_list()

    def add_global_tag(self):
        t_id = simpledialog.askstring("New Tag", "Tag ID:")
        if t_id:
            if "__TextTags" not in self.data:
                self.data["__TextTags"] = {}
            self.data["__TextTags"][t_id] = {"color": "white"}
            self.global_tag_list.insert(tk.END, t_id)


if __name__ == "__main__":
    root = tk.Tk()
    app = TSFGEditor(root)
    root.mainloop()
